// files/resources/js/Components@frontend=react/NoteForm.tsx
import { useForm } from '@inertiajs/react';
import type { SubmitEvent } from 'react';

export default function NoteForm() {
    const form = useForm({
        title: '',
        body: '',
    });

    function submit(event: SubmitEvent<HTMLFormElement>): void {
        event.preventDefault();
        form.post('/notes', {
            preserveScroll: true,
            onSuccess: () => {
                form.reset();
            },
        });
    }

    return (
        <form className="card" noValidate onSubmit={submit}>
            <div className="card-body">
                <h2 className="card-title">New note</h2>
                <div className="field">
                    <label htmlFor="note-title" className="form-label">
                        Title
                    </label>
                    <input
                        id="note-title"
                        type="text"
                        className={form.errors.title ? 'form-control is-invalid' : 'form-control'}
                        value={form.data.title}
                        onChange={(event) => {
                            form.setData('title', event.target.value);
                        }}
                        maxLength={200}
                        required
                    />
                    {form.errors.title && (
                        <div className="invalid-feedback">{form.errors.title}</div>
                    )}
                </div>
                <div className="field">
                    <label htmlFor="note-body" className="form-label">
                        Text (optional)
                    </label>
                    <textarea
                        id="note-body"
                        className={form.errors.body ? 'form-control is-invalid' : 'form-control'}
                        value={form.data.body}
                        onChange={(event) => {
                            form.setData('body', event.target.value);
                        }}
                        rows={4}
                        maxLength={2000}
                    />
                    {form.errors.body && <div className="invalid-feedback">{form.errors.body}</div>}
                </div>
                <button type="submit" className="btn btn-primary" disabled={form.processing}>
                    Add note
                </button>
            </div>
        </form>
    );
}

// files/resources/js/Components@frontend=vue/NoteForm.vue
<script setup lang="ts">
import { useForm } from '@inertiajs/vue3';

const form = useForm({
    title: '',
    body: '',
});

function submit(): void {
    form.post('/notes', {
        preserveScroll: true,
        onSuccess: () => form.reset(),
    });
}
</script>

<template>
    <form class="card" novalidate @submit.prevent="submit">
        <div class="card-body">
            <h2 class="card-title">New note</h2>
            <div class="field">
                <label for="note-title" class="form-label">Title</label>
                <input
                    id="note-title"
                    v-model="form.title"
                    type="text"
                    class="form-control"
                    :class="{ 'is-invalid': form.errors.title }"
                    maxlength="200"
                    required
                />
                <div v-if="form.errors.title" class="invalid-feedback">{{ form.errors.title }}</div>
            </div>
            <div class="field">
                <label for="note-body" class="form-label">Text (optional)</label>
                <textarea
                    id="note-body"
                    v-model="form.body"
                    class="form-control"
                    :class="{ 'is-invalid': form.errors.body }"
                    rows="4"
                    maxlength="2000"
                ></textarea>
                <div v-if="form.errors.body" class="invalid-feedback">{{ form.errors.body }}</div>
            </div>
            <button type="submit" class="btn btn-primary" :disabled="form.processing">
                Add note
            </button>
        </div>
    </form>
</template>
