// files/resources/js/Layouts@frontend=vue/AppLayout.vue
<script setup lang="ts">
import { Link, usePage } from '@inertiajs/vue3';
import { computed } from 'vue';

const page = usePage();
const appName = computed(() => page.props.appName);
const path = computed(() => new URL(page.url, window.location.origin).pathname);
</script>

<template>
    <div class="app">
        <header class="app-header navbar navbar-expand">
            <nav class="container">
                <Link href="/" class="navbar-brand">{{ appName }}</Link>
                <div class="navbar-nav">
                    <Link href="/" class="nav-link" :class="{ active: path === '/' }">Home</Link>
                    <Link
                        href="/notes"
                        class="nav-link"
                        :class="{ active: path.startsWith('/notes') }"
                    >
                        Notes
                    </Link>
                </div>
            </nav>
        </header>
        <main class="app-main container">
            <div v-if="page.flash.success" class="alert alert-success" role="status">
                {{ page.flash.success }}
            </div>
            <slot />
        </main>
    </div>
</template>

// files/resources/js/Layouts@frontend=react/AppLayout.tsx
import { Link, usePage } from '@inertiajs/react';
import type { ReactNode } from 'react';

export default function AppLayout({ children }: { children: ReactNode }) {
    const page = usePage();
    const path = new URL(page.url, window.location.origin).pathname;

    return (
        <div className="app">
            <header className="app-header navbar navbar-expand">
                <nav className="container">
                    <Link href="/" className="navbar-brand">
                        {page.props.appName}
                    </Link>
                    <div className="navbar-nav">
                        <Link href="/" className={path === '/' ? 'nav-link active' : 'nav-link'}>
                            Home
                        </Link>
                        <Link
                            href="/notes"
                            className={path.startsWith('/notes') ? 'nav-link active' : 'nav-link'}
                        >
                            Notes
                        </Link>
                    </div>
                </nav>
            </header>
            <main className="app-main container">
                {page.flash.success && (
                    <div className="alert alert-success" role="status">
                        {page.flash.success}
                    </div>
                )}
                {children}
            </main>
        </div>
    );
}
